### PR TITLE
include FILTERGROUP on fully report cgi url

### PR DESCRIPTION
**Pull request by marcelloc**

### CODE REVIEW

**Comment by fredbcode** [comment]
Philip there are some regressions, takes care at: 
https://github.com/e2guardian/e2guardian/commit/97ec9a80fc187de1ddad7f86f4ab53ada1f5da00
https://github.com/e2guardian/e2guardian/commit/a1d078469f68b689147fe0c3997bfb3cd799a0bc

**Comment by fredbcode** [comment]
Ok fixed in V5

**Comment by philipianpearce** [comment]
Thanks Fred, 

I hope to push a very early test v5 with some draft documentation later today. 

Regards 

Philip 

----- Original Message -----

**Comment by fredbcode** [comment]
Ok great !

----- Mail original -----
> Thanks Fred,
> 
> I hope to push a very early test v5 with some draft documentation
> later today.
> 
> Regards
> 
> Philip

**Pull request merged**
