### PR TITLE
add new option: "xforwardedforfilterip"

### PR DESCRIPTION
**Pull request by GnunuX**
If we add usexforwardedfor option to on, every client can et X-Forwarded-For headers and spoof any IP.
We can now list clients allowed to add X-Forwarded-For headers.

### CODE REVIEW

**Comment by fredbcode** [comment]
There is no entry in Optioncontainer.cpp ? To read the values ?

**Comment by fredbcode** [comment]
I pushed a little change can yo make a try ? Good for you ?

**Comment by GnunuX** [comment]
Sorry for the delay.
In my patch use_xforwardedfor can works without xforwardedforfilterip. In this case, e2guardian read xforwarded header like today.
If we add xforwardedforfilterip, e2guardian read xforwarded header only in selected IP.
I can change my modification if you thinks that xforwardedforfilterip must be set when use_xforwardedfor is set to "on".

**Comment by fredbcode** [comment]
No seems good for me, please can you write some explanations in e2guardianfx.conf

**Comment by GnunuX** [comment]
I'm about to push some more explanations about the option in the config file. But as i understand your merge, you want to make the "xforwardedforfilterip" option mandatory as soon as the "xforwardedfor" option is enabled. Well, maybe that is not necessary. You should let the user configure the proxy as he wishes, at his own risk. Especially that there already is a warning in the config file about "xforwardedfor" spoofing potential. What do you think ?

**Comment by fredbcode** [comment]
Ok right, can you make this change ? I can't do now 
Thanks

**Comment by fredbcode** [comment]
Ok I removed any control, the default size is < 0, so without value xforwardedfor_filter_ip is disabled.

Please push some more explanations

**Comment by fredbcode** [comment]
https://github.com/e2guardian/e2guardian/commit/cf10d9c7960a2a6673d1053132c7fa1b57c5045b
No exit when the value is not entered, xforwardedfor_filter_ip is just disabled 
See https://github.com/e2guardian/e2guardian/blob/develop/src/ConnectionHandler.cpp#L869

Not yet tested

**Pull request merged**
