### PR TITLE
Logger

### PR DESCRIPTION
**Pull request by KDGundermann**
First try for a central Logger.
I would be happy about some feedback.
If it is OK I would implement it in the project ( and delete about 2000+ lines, making the code better readable )

### CODE REVIEW

**Review by philipianpearce — CHANGES_REQUESTED** [review]
Thanks for your work on this.   Some needed changes/suggestions follow.

We would only change the build platform on a major version change.

Moving to c++14 at this stage would cause problems for implementations with existing stable o/s bases as is likely to require major o/s upgrades on customers systems or at the least the distribution of revised c++ stdllib libraries.

What is the reason for doing this?  (As far as I can see all the needed features are in c++11).

Macro definitions by convention should all be in upper case - this alerts other developers that it is a macro rather than a normal function. 

The Logger* __logger may need to be declared as an extern at the start of each module that uses it, otherwise link errors are likely.

The adding of source function and line numbers should be made an option.  For most straight error messages it is confusing for a user. 
Although sometimes helpful in debuging,  more often it makes the debug log harder to scan and read. (We have tried it before!).  If present the function/line number should be at the end of the line rather than at the beginning.

Each line should start with the thread_id as it shows which thread the message is from.   There is no need to pass in a function call as it is a global (but thread_local).

The LOGGER_DEBUG macro must be defined to blank if E2DEBUG is not set to avoid unnecessary  stack pushes and cpu processing in production systems.

The string + string + string being used to call the macros is has  a number of problems.  My ide warns against using this as it is very inefficient.     Also it means all parameters have to be converted to string type before calling the macro.   A neater solution would be to use functions with a variable number of parameters and then assemble the message line using a modified build_message function.   I will send an example of this later. 

Regards
Philip

**Comment by KDGundermann** [comment]
Hi Philip,

thank you for your feedback. See my comments inline:

> Moving to c++14 at this stage would cause problems for implementations with existing stable o/s bases as is likely to require major o/s upgrades on customers systems or at the least the distribution of revised c++ stdllib libraries.
> What is the reason for doing this? (As far as I can see all the needed features are in c++11).

I think we can agree that C++ strings are safer to use as the old C char[] style strings. But sadly only with C++14 it is possible to declare std::string literals. I thought it would be safe to use a standard which is now 6 years old :-)

 
> Macro definitions by convention should all be in upper case - this alerts other developers that it is a macro rather than a normal function.

Didn't know about that, I'm usual using upper case for Const declarations only.  E.g. as shown in [cplusplus-Tutorial](http://www.cplusplus.com/doc/tutorial/preprocessor/)
 
> The Logger* __logger may need to be declared as an extern at the start of each module that uses it, otherwise link errors are likely.  

I've included the declaration in Logger.h so it will be included in each module

> The adding of source function and line numbers should be made an option. For most straight error messages it is confusing for a user.
> Although sometimes helpful in debuging, more often it makes the debug log harder to scan and read. (We have tried it before!). If present the function/line number should be at the end of the line rather than at the beginning.

Thats why I wanted to have all logging in a central module, so we can configure the output to our demands.
( and as I'm currently try to understand the control flow of e2guardian it helps me a lot to trace the current function name and line#. )

> Each line should start with the thread_id as it shows which thread the message is from. There is no need to pass in a function call as it is a global (but thread_local).  

OK, will change it.

> The LOGGER_DEBUG macro must be defined to blank if E2DEBUG is not set to avoid unnecessary stack pushes and cpu processing in production systems.  

I thought the compiler will remove an empty function anyway, but  I discovery right now that this is only true for CLANG 5.0 / GCC 10.1 :-((

> The string + string + string being used to call the macros is has a number of problems. My ide warns against using this as it is very inefficient. Also it means all parameters have to be converted to string type before calling the macro. A neater solution would be to use functions with a variable number of parameters and then assemble the message line using a modified build_message function. I will send an example of this later.

An example would be very helpful, as I couldn't figure it out how to work with a variable number of parameters 

Best regards
Klaus

**Comment by KDGundermann** [comment]
I have just discovered the "DebugManager".  
I'm correct to say, the intent of the DebugManager is to allow users to debug some parts of the application (ICAP,ICAPC,THTTPS,PROXY)  (but why not Storyboard?) without compiling it with the E2DEBUG flag?

I have already thought of "tagging" the log messages, so that you can enable/disable them (see e.g.  Logger::story)

As far as I can see the DebugManager will only write in a local logfile? As we are running our applications dockerized with a central logging framework (GrayLog + Kibana) I would prefer to have logs written either to stdout/stderr (docker)  or to syslog (native).

Should I prepare an example how to integrate it in Logger ?

**Comment by philipianpearce** [comment]
Hi Klaus, 

Yes, i agree C++ strings are safer that c string (char *). The majority of string handling in e2g is done using the String class which is based in std::string. However, when literals are used in assignments (to a std::string the complier will automatically convert them to a C++ string anyway so this is safe, without implicitly using the 's' suffix. I suspect that the later compilers also read the literal text as a c-str and then apply any prefix or suffix conversion. 

Where e2g is used on an appliance (as we do) long-life versions of o/s are used (which are supported for 5 years plus from release date). When we started using C++11 in 2016, I had difficulty finding a stable distribution which fully supported the C++11 standard and so had to compile and distribute the whole C++11 library to our clients systems! Changing mid-major version also means that all developers using e2g would have update their build environment and their target environments. So we will have to wait for v6 to update to C++14 or later. 

I would prefer that we use upper case for preprocessor functions as this is the convention used in e2g (and particularly in openssl). The only exception from this is where a defined function is used to overwrite or emulate a system or library call. This has helped me to avoid got yahs on a number of occasions. 

A variable number of parameters (of different types) can be passed using variadic templates. 

I attach an example based on your original Logger class. I have just added a template for vdebug and a cat_all_vars template as a build_message replacement as an example in Logger.hpp. 
I've only changed the logic for debug() call. 

I've tested and it works as expected. 

Best wishes, 
Philip 
----- Original Message -----

**Comment by philipianpearce** [comment]
The DebugManager code was written by a colleague of Fred's a couple of years ago as he wanted a way of switching off/on various debug in various parts of the code in runtime versions. It has only been implemented in a couple of code sections mainly those surrounding ICAP. My concern is for runtime efficiency, especially as many of the low level functions are called repeatedly (It can 1000's of times for a single request) hence the NEWDEBUG_OFF flag which enables me to remove the calls on production systems. 

Yes, it would be good to integrate it into the new Logger especially if we use the preprocessor trick to blank the the calls if NEWDEBUG_OFF is set. 

You will have noticed that I have replaced E2DEBUG with more specific directives in low level and/or very repeated code. e.g NETDEBUG SBDEBUG etc.. The reason for this is to reduce the volume of debug output so that it is readable and useful for debugging what happens to an individual set of user requests. I only turn these on when I am working on the appropriate low level code. So it is very important that these are preserved. Maybe with a distinct macro for each type, so that the call disappears when the appropriate directive is absent. 

For example, there is a storyboard trace feature. It is designed to be used on a test system with just a single user. Just having this switched on without debug on a test system with 1 user, can flood syslog. So I would not advise debug output be sent to any centralised logging system! The original version of DebugManager also used syslog, but this was found to be impractical due to volume issues, and that is why is goes to a local file. 

So, we need the ability for different types of logging to go to different places, so for example error/log would go to syslog or stderr by default (depending on setting of is_demonised), but it debug is on then it is also sent to where debug is output (normally stderr). 

And Storyboard tracing can be sent to somewhere else if needed. 

Debug output is better to stderr or to a unbuffered file. Otherwise, if you are trying to debug in a crash situation, the messages just before the crash are lost (anything in the i/o buffers are lost). 

So I would suggest a set of output flags per category of log rather than one set for all. 

I notice you have 'log' and 'trace' what is the distinction? 'log' and 'error' always on, but 'trace' an option? 

Thanks, 
Philip 
----- Original Message -----

**Comment by KDGundermann** [comment]
Hi Philip,

I will try to prepare the logger with different logging tags and output destinations tomorrow.

> I notice you have 'log' and 'trace' what is the distinction? 'log' and 'error' always on, but 'trace' an option?

- log: used for output of the application to the user (in production)
- trace: I use it for following the program FLOW (in debug mode)
- debug: I use it to out program DATA (in debug mode)

> I attach an example based on your original Logger class.

Where can I find the attachment?

**Comment by philipianpearce** [comment]
> 
> Where can I find the attachment?

I attached to the email - seems that github removes attachments.


[Logger.hpp.gz](https://github.com/e2guardian/e2guardian/files/4850418/Logger.hpp.gz)
[Logger.cpp.gz](https://github.com/e2guardian/e2guardian/files/4850422/Logger.cpp.gz)

**Comment by KDGundermann** [comment]
I've added a LoggerConfigurator so you can configure every logger tag (either on commandline or in e2guardian.conf) with:
`log_{source}={output}[, filename]`

**Comment by KDGundermann** [comment]
Hi Phillip, would you like to merge my branch into v5.4.dev ?
( but I think we will have a conflict on OptionContainer.cpp which you have changed just now :-(  )

**Comment by KDGundermann** [comment]
Hi Philip, where should I put some HOWTO text for the Logger/LoggerConfigurator class ?

**Comment by philipianpearce** [comment]
Hi Klaus,   Create a HOWTO_Logger file in the notes directory.

**Comment by philipianpearce** [comment]
> Hi Phillip, would you like to merge my branch into v5.4.dev ?
> ( but I think we will have a conflict on OptionContainer.cpp which you have changed just now :-( )

Hi Klaus,

I have started the merge, but I'm going to put result in new branch v5.4.Logger.   

I'm currently preparing v5.4.dev for a final pre-release for v5.4 (I have already got v5.4 running on production systems, so there can be no breaking changes).  This will include the changes I have made to enable .Include<> and .Pwd<> in config files, and your relative path code.  I believe this is safe to do on a near production release as they only affect the reading of config files, are fully compatible with previous v5.4 versions and have no affect on the critical running code.

I have been actively working on v5.5 for about 3 months.  This already includes a code clean-up and the re-writing of the network i/o to non-blocking and some code improvements to DataBuffer and re-write of DownloadManager plug-in. I was hoping to able to release an experimental v5.5 release shortly so that all of this can be fully tested.

So what I am intending to do, is wait until we are happy with v5.4.Logger.    Then apply a straight diff between v5.4 and v5.4.Logger to v5.5.dev.    I know this is likely to involve a lot of manual merging due to the existing major code changes in v5.5

Then release the v5.5 experimental release with the Logger included.

Regards
Philip

**Comment by KDGundermann** [comment]
Hi Philip, 
should I rebase Logger on v5.5.dev ?
PS: I have some questions regarding the code, should I ask them here or in the google group or do you have something else? (e.g. Slack)

**Comment by KDGundermann** [comment]
main task done!
next steps:
- remove obsolete code (e.g. DebugManager, what should I do with code in #NEWDEBUG_OFF ??)
- refactor dstat to output data over Logger
- rework ConnectionHandler::doLog, FatController::log_listener (maybe in another branch..)

**Comment by fredbcode** [comment]
Hello,

You can check the test process here: https://gitlab.com/fredbcode/e2guardian/-/pipelines
Error detailed: https://gitlab.com/fredbcode/e2guardian/-/jobs/625275625

Regards
Fred

**Comment by KDGundermann** [comment]
Hi Fred,

ok it tells me: `Unable to load plugin config: admanagers/default.conf`  
Where is the `admanagers/default.conf` coming from?

**Comment by philipianpearce** [comment]
Hi Klaus,


I have changed the .Pwd into .Define LISTDIR in order to make it's purpose clearer (in v5.4.dev and also in v5.4.Logger and v5.5.dev)

I have now finished merge of Logger  into v5.4.Logger and have pushed this to github.

I have also brought v5.5.dev up-to-date with changes in v5.4.dev and pushed to github.

Great that you have done the main work!

I will review and test as a whole over the next few days and then feed back any changes I think may be needed.

Yes, it would be very helpful if you would rebase Logger on v5.5.dev.



Also, answers to your questions:-

    remove obsolete code (e.g. DebugManager, what should I do with code in #NEWDEBUG_OFF ??)

The code after ifndef  NEWDEBUG_OFF has similar function to Logger.  Just need the macro call to be able to be blank if
NEWDEBUG_OFF is defined.   I'll give you more detail once I've reviewed how you are actioning these at the moment.

    refactor dstat to output data over Logger

Can't really see why we should need to do this at the moment and output format can't change.  I suppose there may be a case to have an option to syslog or stdout but it would be next to useless without being able to read consecutive lines and also dstat provides critical information in high load situations where syslog and stdout are likely to be flooded.

    rework ConnectionHandler::doLog, FatController::log_listener (maybe in another branch..)

What changes are you thinking of here?    The general access.log is via a queue so I don't see it as using Logger, and already has option to put to syslog.

Thanks
Philip

**Comment by philipianpearce** [comment]
This pull request has been merged in a new branch of v5.4.dev called v5.4.Logger.

**Comment by philipianpearce** [comment]
It's a fault in the config - I will correct. 

Philip 

----- Original Message -----

**Comment by KDGundermann** [comment]
Hi Phillip and Fred,

> This pull request has been merged in a new branch of v5.4.dev called v5.4.Logger

So you plan to release a 5.4 version with Logger? I Thought you will postpone it to 5.5 ?

> refactor dstat to output data over Logger

I want to simplify the configuration of e2guardian ( sorry, but I think the configuration is way to complex for a beginner to understand.  e2guardian.conf + e2guardianf1.conf with 1300+ lines plus 460 story lines.. )
So enabling the dstat would be as simple as :
`log_dstat=dstat.log`

> rework ConnectionHandler::doLog, FatController::log_listener (maybe in another branch..)

The FatController is way to fat ;-) and log_listener with 600+ lines in a single method  (and ConnectionHandler::DoLog/doRQLog with 600 lines) too. 
So I would like to refactor this in its own class and simplify it.

Klaus

PS: I have still some spare time this week, so where should I proceed? Rebase on v5.5.dev, and then I would like to remove DebugManager, ... ????

**Comment by philipianpearce** [comment]
> So you plan to release a 5.4 version with Logger? I Thought you will postpone it to 5.5 ?
Yes, Logger in v5.5 for main release pre/stable flow.

v5.4.Logger is for anyone who wants to test/contribute to Logger now, as it is based on near-stable v5.4.
I will use it for my testing etc this week.
> 
> > refactor dstat to output data over Logger
> 
> I want to simplify the configuration of e2guardian ( sorry, but I think the configuration is way to complex for a beginner to understand. e2guardian.conf + e2guardianf1.conf with 1300+ lines plus 460 story lines.. ).  

I agree, that the config is complex, and not easy to read.    It is also my aim to simplify the config, and I have already removed many config options over the last few releases.    Many of the config options will not (normally) need to be touched by a user, so can be put in Include<> files.   As a first stage in v5.5 I will classify the options into groups.   And the sample list structure needs documenting.    This was why I introduced .Includes<> in the .conf flles in v5.4 and the LISTDIR in preparation. With these two options, the work on the .conf files and smple list structure can be done without any further binary changes.
 
> So enabling the dstat would be as simple as :
> `log_dstat=dstat.log`

?? How is this different to the current option?  Apart from a change of name?

> 
> The FatController is way to fat ;-)

Yes, I agree, I inherited it, with more than double the number of lines it has now.

> and log_listener with 600+ lines in a single method (and ConnectionHandler::DoLog/doRQLog with 600 lines) too.
> So I would like to refactor this in its own class and simplify it.

That is a good idea but it would need two classes one for DoLog/doRQLog and one for log_listener which runs in its own thread(s).  (The doRQlog was a quick safe kulge in order to do some debuging on live systems and needs re-visiting anyway)
 
> PS: I have still some spare time this week, so where should I proceed? Rebase on v5.5.dev, and then I would like to remove DebugManager, ... ????

Yes, that would be great!

For code queries, you can email me directly  philip at e2bn.org.

Thanks
Philip

**Pull request closed without merging**
