### PR TITLE
complete translation for ptbrazilian file

### PR DESCRIPTION
**Pull request by marcelloc**

### CODE REVIEW

**Comment by fredbcode** [comment]
Thanks

**Comment by marcelloc** [comment]
The updated translate file is missing on the other pull request. So I've opened this. 
Can you reopen it to merge?

**Comment by fredbcode** [comment]
Hum, on master ? Not retryfix ?

**Comment by marcelloc** [comment]
My mistake. Sorry. I'll push on right repo.

**Pull request merged**
