### PR TITLE
Include template for neterr which was missing

### PR DESCRIPTION
**Pull request by forid786**
Added neterr_template.html required so that E2 Guardian can properly show an error when it is unable to load a page (UK English). This should help resolve issue #432 .

### CODE REVIEW

**Comment by forid786** [comment]
When attempting to merge into v5 Develop and other branches, I am still getting some conflicts. :(

@philipianpearce @fredbcode

**Comment by fredbcode** [comment]
You must make a git pull before your changes, and add only your changed files (git add file)
git status show the local files with your modifications

However you can send the file with pm if needed




----- forid786 <notifications@github.com> a écrit :

**Comment by forid786** [comment]
@fredbcode As you can probabily tell, I'm not an expert on git yet. xD

I assume you want me to install the git program and then run those commands? The modifications that I've done so far have all been done through the website.

While I'm still learning, can you copy and paste and create the file for me? Just drop it into the UK English language directory.

**Comment by fredbcode** [comment]
Good now, without conflict :), ok applied

**Pull request merged**
