### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by prlw1**
- Leave creation of Makefile.in etc to autogen.sh, or make dist.
- Make use of epoll.h more obvious - when I first read the code I thought parts really were linux specific, rather than use-of-epoll specific.

### CODE REVIEW

**Comment by fredbcode** [comment]
Ok thanks, I will take a look 
FYI epoll is Linux only

> when I first read the code I thought parts really were linux specific, rather than use-of-epoll specific.

So It's linux specific

Have you added something in dist-clean (makefile.am I guess) to removes files generated by autogen.sh ?

**Comment by prlw1** [comment]
You can use epoll if you have sys/epoll.h. It is only "linux specific" in the sense that you won't find sys/epoll.h on my NetBSD box. "Test for features" (not versions, OSes etc)

"Remove files generated by autogen.sh" from the git repository.

**Comment by fredbcode** [comment]
At least there is something new but Epoll was Linux only (related to kernel) BSD are using kqueue
Do you have more informations ?

> "Remove files generated by autogen.sh" from the git repository.

Ok thanks, I will take a look to remove the files with make distclean, they have already been removed ...

**Comment by prlw1** [comment]
Epoll may well be linux only at the moment, but you want to test for epoll, not for linux. (AGain: test for features, not versions or OSes) (This should be obvious if you look at the patch...)

If the autogenerated files really have already been removed from the repository, why do I see:

$ git log autom4te.cache/requests 
commit 832107c3fb6308136f0181abd14eb5756bf729e5
Author: fredbcode <stealth@altern.org>
Date:   Tue Jan 6 17:38:43 2015 +0100

    Fix crash with: groupe 0 and SSL Filter
...

What on earth is autom4te.cache/requests doing in the git repository?

Again, the patch is trivial - just have a look...

**Comment by fredbcode** [comment]
> If the autogenerated files really have already been removed from the repository, why do I see

I mean before, but the files was re-pushed after, I fixed the "make disctclean" (and updated gitignore) I will push a fix. I hope I forgot nothing.

> Epoll may well be linux only at the moment, but you want to test for epoll, not for linux

I understand right (and I saw your patch) the problem is that Epoll is not enough explicit for all
Maybe we should also add a comment to be more clear (something like LINUX FEATURE) 

For example, you can try to make epoll works in your BSD box

**Pull request merged**
