### PR TITLE
Problem with permissions while creating (sub)directorys!

### PR DESCRIPTION
**Pull request by tachtler**
Hi,

FIRST OF ALL, I'm NOT an C++ programmer, so sorry maybe for bad/wrong syntax!

The ideas are from here: http://blog.tremend.ro/2008/10/06/create-directories-in-c-using-mkdir-with-proper-permissions/

Maybe, some changes on the specific code, could solve the problem while creating the (sub)directory where the certificate files are stored?

Thank you for checking that!
Klaus.

### CODE REVIEW

**Comment by philipianpearce** [comment]
Klaus, 

A call to umask(0) is already made on e2guardian initialization and so adding it before the mkdir() call is not needed. Also, if it is a coding error the file permissions would be wrong every time, so it is more likely that the problem is on the operating system level. 

I have seen similar odd file permissions issues, when secure linux is enabled. If it is on your system, try disabling it or setting it to permissive mode . 

Regards 

Philip 

----- Original Message -----

**Comment by tachtler** [comment]
Hi Philip,

> Klaus,
>
> A call to umask(0) is already made on e2guardian initialization and 
> so adding it before the mkdir() call is not needed. Also, if it is a 
> coding error the file permissions would be wrong every time, so it is 
> more likely that the problem is on the operating system level.

o.k. I doesn't know that.

> I have seen similar odd file permissions issues, when secure linux is 
> enabled. If it is on your system, try disabling it or setting it to 
> permissive mode .

The server50 are still running with selinux disabled. So this is not the
problem. 

[root@server50 ~]# getenforce 
Disabled

Thank you for your help to solve the problem!

Klaus.

**Comment by fredbcode** [comment]
Philip, maybe there is a specific problem with the dev branch ?
I found something close recently with commandline scan and Debian

umask(S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP);

Should be

mode_t mask = umask(S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP);
umask(mask);

https://github.com/e2guardian/e2guardian/commit/5ea2dd5379105752b6ad477fa33ccad6b8c1ceb8

**Comment by fredbcode** [comment]
@tachtler  Have you done a test with your patch ?
Do you have something in kern.log ?

**Comment by tachtler** [comment]
Hi Fred,

nice to hear something again from you!

No, I did not make a test with my patch, because I'm not sure that the syntax was right? But I can give my patch a try, if you say the syntax is o.k.?

I only have some messages in ```/var/log/messages``` or in ```dmesg```, see:
```
Jul  1 09:54:17 server50 e2guardian[10880]: Started sucessfully.
Jul  1 09:55:30 server50 e2guardian[10940]: error creating certificate sub-directory
Jul  1 09:56:09 server50 e2guardian[10883]: error creating certificate sub-directory
Jul  1 09:56:46 server50 kernel: e2guardian[10972]: segfault at 7ea00 ip 00007f83a3b35ebc
sp 00007ffce5629780 error 4 in libcrypto.so.1.0.1e[7f83a3a54000+1bd000]
Jul  1 09:56:54 server50 systemd: Stopping E2guardian Web filtering...
Jul  1 09:56:55 server50 systemd: Stopped E2guardian Web filtering.
```

```
[266076.739147] e2guardian[9969]: segfault at bbd10 ip 00007f5769be8ebc sp
00007ffccad0a600 error 4 in libcrypto.so.1.0.1e[7f5769b07000+1bd000]
[266634.932310] e2guardian[10972]: segfault at 7ea00 ip 00007f83a3b35ebc
sp 00007ffce5629780 error 4 in libcrypto.so.1.0.1e[7f83a3a54000+1bd000]
```

Thank you for your help!
Klaus.

**Comment by fredbcode** [comment]
I'm not familiar with Centos, do you have something strange in some other logs ? Maybe a message without direct relation ...

Yes I think you can make a try, but with a little change please

int rc = mkpath(dirpath.c_str(), S_IRWXU | S_IRWXG | S_IRWXO);

Change this part by

mode_t mask = umask(S_IRWXU | S_IRWXG | S_IRWXO);
int rc = mkpath(dirpath.c_str(), mask);

 S_IRWXO is insecure but it's only for testing purposes

**Comment by tachtler** [comment]
Hi Fred,

I changed my patch-2 (pull-request) as you said. I downloaded the development-branch as zip, changed the  src/CertificateAuthority.cpp like the pacth-2.

My colleague will build a rpm for me, and we will give them a try. I will report the result.

Thank you!
Klaus.

**Comment by fredbcode** [comment]
There is also a problem with the segmentation fault at exit

**Comment by tachtler** [comment]
Hi Fred,
hi Philip,

the result of the patch is a disaster, look:
```
# ls -la /var/lib/ssl_e2guardian/
total 4
drwxr-xr-x   9 e2guardian e2guardian   69 Jul  1 14:34 .
drwxr-xr-x. 26 root       root       4096 Jul  1 14:22 ..
d---------   2 e2guardian e2guardian    6 Jul  1 14:33 06
d---------   2 e2guardian e2guardian    6 Jul  1 14:33 0E
d---------   2 e2guardian e2guardian    6 Jul  1 14:33 20
d---------   2 e2guardian e2guardian    6 Jul  1 14:33 57
d---------   2 e2guardian e2guardian    6 Jul  1 14:34 84
d---------   2 e2guardian e2guardian    6 Jul  1 14:33 D6
d---------   2 e2guardian e2guardian    6 Jul  1 14:33 EA
``` 
But now, we know that on this piece of code, we can do something, or I'm wrong?

Thank you all!
Klaus.

**Comment by fredbcode** [comment]
Of course, it was stupid ...
Please try your original pacth, with some changes 

 add line 162

mode_t mask = umask(S_IRWXU | S_IRWXG | S_IRWXO);
umask (mask);

Remove the lines 402 and 404 and 407 restore the original code

I'm sorry I can't test code now, I'm just reading the code on github

**Comment by tachtler** [comment]
Hi Fred,
hi Philip,

changed the line 163 to:
```
int rc = mkpath(dirpath.c_str(), S_IRWXU | S_IRWXG | S_IROTH | S_IXOTH);
```
AND IT WORKS!

No wrong file permissions!

Thank you for your help.
Klaus.

**Comment by tachtler** [comment]
Hi Fred,
hi Philip,

changed the patch-2 too.

Klaus.

**Comment by tachtler** [comment]
Hi Fred,
hi Philip,

the line 402, 403, 404 are like I changed it. Please see the patch-2.

Thank you!
Klaus.

**Comment by fredbcode** [comment]
Ok great, I think there was also a problem with mkdir resolved by your fix.

If you have time can you make a try with my changes - in my last comment -, I like to know if umask() can fix also the problem.  

A try with an umask BEFORE mkpath and mkdir 

int mkdir(const char *pathname, mode_t mode);
...
The argument mode specifies the permissions to use. It is modified by the process’s umask in the usual way: the permissions of the created directory are (mode & ~umask & 0777).

**Comment by tachtler** [comment]
Hi fred,

yes, we can do this, BUT can you give me the code lines and changes I have to make, that will be great, thank you!

Klaus.

**Comment by fredbcode** [comment]
Thanks

Something like this (sorry I can't do a patch now)
With the Philip 's code, add the two lines 

mode_t mask = umask(S_IRWXU | S_IRWXG | S_IRWXO);
umask (mask);

Just before: 

int rc = mkpath(dirpath.c_str(), 0777);

Like this:

int rc = mkpath(dirpath.c_str(), 0777);
mode_t mask = umask(S_IRWXU | S_IRWXG | S_IRWXO);
umask (mask);

**Comment by tachtler** [comment]
Hi Fred,

Of course, I can do this...

Do you mean:
<h3>A</h3>
```
int rc = mkpath(dirpath.c_str(), 0777);
mode_t mask = umask(S_IRWXU | S_IRWXG | S_IRWXO);
umask (mask);
```

OR

<h3>B</h3>
```
mode_t mask = umask(S_IRWXU | S_IRWXG | S_IRWXO);
umask (mask);
int rc = mkpath(dirpath.c_str(), 0777);
```

Klaus.

**Comment by fredbcode** [comment]
B - Please

**Comment by tachtler** [comment]
Hi Fred,

sorry, for my question - line 402, 403 and 404 reset to the original code from Philip?

Klaus.

**Comment by fredbcode** [comment]
Yes exact, I'm just curious 

This two lines 

    mode_t mask = umask(S_IRWXU | S_IRWXG | S_IRWXO);
    umask (mask);

Fix the problem ?

**Comment by tachtler** [comment]
Hi Fred,

<h2>SUMMARY</h2>

line start at 162:
```
    // make directory path
    mode_t mask = umask(S_IRWXU | S_IRWXG | S_IRWXO);
    umask (mask);
    int rc = mkpath(dirpath.c_str(), 0777);
        if (rc != 0) {
        syslog(LOG_ERR,"error creating certificate sub-directory");
        exit(1);
    }
```

lien start at 397:
```
int CertificateAuthority::do_mkdir(const char *path, mode_t mode)
{
    struct stat st;
    int status = 0;

    if (stat(path, &st) != 0)
    {
        /* Directory does not exist. EEXIST for race condition */
	if (mkdir(path, mode) != 0 && errno != EEXIST)
            status = -1;
    }
    else if (!S_ISDIR(st.st_mode))
    {
        errno = ENOTDIR;
        status = -1;
    }

    return(status);
}
```

Is that right, like you need it?

Klaus.

**Comment by fredbcode** [comment]
Yes seems like the original code, good

**Comment by tachtler** [comment]
Hi Fred,

we will try this... I will report you!

Klaus.

**Comment by tachtler** [comment]
Hi Fred,

it works!

```
# ls -la /var/lib/ssl_e2guardian/
total 4
drwxr-xr-x  16 e2guardian e2guardian  132 Jul  1 16:17 .
drwxr-xr-x. 26 root       root       4096 Jul  1 14:22 ..
drwxrwxr-x   4 e2guardian e2guardian   24 Jul  1 16:17 06
drwxrwxr-x   3 e2guardian e2guardian   15 Jul  1 16:16 0A
drwxrwxr-x   3 e2guardian e2guardian   15 Jul  1 16:16 0E
drwxrwxr-x   3 e2guardian e2guardian   15 Jul  1 16:16 20
drwxrwxr-x   3 e2guardian e2guardian   15 Jul  1 16:17 4B
drwxrwxr-x   3 e2guardian e2guardian   15 Jul  1 16:17 53
drwxrwxr-x   3 e2guardian e2guardian   15 Jul  1 16:16 57
drwxrwxr-x   3 e2guardian e2guardian   15 Jul  1 16:16 6C
drwxrwxr-x   3 e2guardian e2guardian   15 Jul  1 16:16 7A
drwxrwxr-x   3 e2guardian e2guardian   15 Jul  1 16:16 84
drwxrwxr-x   3 e2guardian e2guardian   15 Jul  1 16:16 9B
drwxrwxr-x   3 e2guardian e2guardian   15 Jul  1 16:16 A5
drwxrwxr-x   3 e2guardian e2guardian   15 Jul  1 16:16 C3
drwxrwxr-x   3 e2guardian e2guardian   15 Jul  1 16:17 FD
```

Great job, thank you!
Klaus.

**Comment by tachtler** [comment]
Hi Fred,

updated my last pacth-2 to the steps you told me. So you can copy it and commit it, that will be great, because we will build a new rpm tomorrow, when your changes committed.

Thank you so much, so we can continue testing.
Klaus.

p.s. It's not for production - only for testing we know - it's development branch!

**Comment by fredbcode** [comment]
Ok, Thanks for your help,
Philip I know you are working on SSLMITM, so I pass on the baton for the commit, if you think it's good or not with your recent changes.

Not related, if you agree I will totally remove max_upload_size from e2guardian.conf, I was recently confused about this, with the new logic this value should be only in e2guardianfx.conf

**Comment by fredbcode** [comment]
Oups I forgot, sorry now can you just make a test without S_IRWXO

mode_t mask = umask(S_IRWXU | S_IRWXG) ;

and 

int rc = mkpath(dirpath.c_str(), 0770);

I think we should reduce the rights, only for E2 user

**Comment by tachtler** [comment]
Hi Fred,
hi Philip,

I downloaded the latest e2guardian-develop.zip and changed line <b>163,164 and 165</b> as follows:
```
mode_t mask = umask(S_IRWXU | S_IRWXG);
umask (mask);
int rc = mkpath(dirpath.c_str(), 0770);
```
So we will build a new rpm and start testing with it. I will report the results.

Klaus.

**Comment by tachtler** [comment]
Hi Fred,
hi Philip,

<h3>it works!</h3>

See the following generation of the directories and sub directories:
```
# ls -la /var/lib/ssl_e2guardian
total 8
drwxr-xr-x  57 e2guardian e2guardian 4096 Jul  2 09:31 .
drwxr-xr-x. 26 root       root       4096 Jul  2 03:32 ..
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 01
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 03
drwxrwx---   4 e2guardian e2guardian   24 Jul  2 09:31 06
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 07
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:30 0A
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 0B
drwxrwx---   4 e2guardian e2guardian   24 Jul  2 09:31 0E
drwxrwx---   4 e2guardian e2guardian   24 Jul  2 09:31 0F
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 10
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 16
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 1D
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:30 20
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 21
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 25
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 27
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 2A
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:29 34
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 38
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:29 3E
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 47
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 49
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 4F
drwxrwx---   4 e2guardian e2guardian   24 Jul  2 09:31 50
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 52
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:30 53
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:30 57
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 58
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 61
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 63
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 65
drwxrwx---   6 e2guardian e2guardian   42 Jul  2 09:31 66
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 6B
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 75
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 7B
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 7F
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 82
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 90
drwxrwx---   4 e2guardian e2guardian   24 Jul  2 09:31 91
drwxrwx---   4 e2guardian e2guardian   24 Jul  2 09:31 9B
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 9E
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 A2
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:29 A5
drwxrwx---   4 e2guardian e2guardian   24 Jul  2 09:31 AD
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 AE
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 B1
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:30 B2
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 B8
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 BC
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:30 C3
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 E4
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 E6
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 F7
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 F8
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 FC
drwxrwx---   3 e2guardian e2guardian   15 Jul  2 09:31 FD
```

Thank you!
Klaus.

**Comment by fredbcode** [comment]
Ok great, I think it's better like this
Now wait, I hope Philip will finds time to take a look. As I said I'm not familiar with SSLMITM and Philips works hard to the code right now, so I prefer don't touch this part just to avoid any possible confusion, at least until we release our next version.

**Comment by tachtler** [comment]
Hi Fred,

I agree totally with you. Maybe Philip could watch the changes and commit the patch-2 or create his own patch or something like that. Our interest is to help, making e2guaridan a better replacement for DansGuardian!

Thank you so much for your help!
Klaus.

**Comment by fredbcode** [comment]
Philip, after ContentScanner.cpp and CertificateAuthority.cpp I think that there is the same potential problem in

BackedStore.cpp
DataBuffer.cpp

In my case (AV scanning), the problem happened randomly.
If you agree I can put the same changes

**Comment by fredbcode** [comment]
Hi Tachtler 
Dev branch still good for you ? no problem with SSLMITM ?

**Comment by tachtler** [comment]
Hi Fred,

every thing works as expected. My configuration is for public view at:
(Sorry it's only available in German language)

http://www.dokuwiki.tachtler.net/doku.php?id=tachtler:e2guardian_centos_7 

Greetings
Klaus.

**Comment by fredbcode** [comment]
It looks really good, any plan for translation ?

**Comment by tachtler** [comment]
Hi Fred,

thank you!

Until now, there are no plans to translate the DokuWiki into English, but maybe one day, when I have lot's of spare time...?!?

Greetings
Klaus.

**Comment by fredbcode** [comment]
Ok the latest fixes from Philip are merged now, maybe the last step before release
Can you make a test please ?

**Comment by tachtler** [comment]
Hi Fred,

the rpm-package are still build, but I will test this tomorrow and give you a report.

Greetings
Klaus.

**Comment by tachtler** [comment]
Hi Fred,
hi Phiip,

great work, works as expected. Content filter and MITM, before squid works. Tested with one user at a new CentOS-7 Server, by myself. (Sorry, only a very small setup are till now available).

Thank you!

**Pull request closed without merging**
