### PR TITLE
Make per room blocking optional (C++ implementation)

### PR DESCRIPTION
**Pull request by prlw1**
I wrote this version for dansguardian, then discovered e2guardian, see that per room blocking has already been made optional in e2guardian, but think that this version is cleaner from a real C++ point of view.

### CODE REVIEW

**Comment by prlw1** [comment]
I can't see the merge of this pull request - what happened to it?

**Comment by fredbcode** [comment]
| I can't see the merge of this pull request - what happened to it? 

It's in dev branch, not exactly merged but adapted 

Thank

**Comment by prlw1** [comment]
I see! The code in the "develop" branch looks much better - so "master" is some sort of stable branch rather than bleeding edge?  (I'm used to master / HEAD being bleeding edge, with stable branches - so how does this work for e2guardian?)

**Comment by fredbcode** [comment]
| I see! The code in the "develop" branch looks much better - so "master" is some sort of stable branch rather than bleeding edge? (I'm used to master / HEAD being bleeding edge, with | stable branches - so how does this work for e2guardian?)

Master is the stable release, usually without the latest features should be more stable  
Dev is the "unstable" release, new codes, new features (eg SSLMITM), new problems

Actually there is also nosslsearch this is an interim version but we should remove this branch later.

There are many major changes (and bug fixes) in Dev branch, but we are not ready to release now, I hope soon

**Pull request closed without merging**
