### PR TITLE
Replace some translations in the Spanish language.

### PR DESCRIPTION
**Pull request by leo95batista**
Hello, thank you very much for the excellent work you have done so far. I would like to do my bit and I do it with this PR.

My native language is Spanish and I have seen that many translation messages that e2guardian uses when setting Spanish as the default language used English translations.

With this PR I intend to modify some translation strings in the message file of the Spanish language. In this way when a user establishes that the language to use is Spanish, then the messages in this language are displayed correctly.

### CODE REVIEW

**Comment by philipianpearce** [comment]
Many thanks for the translations!   Philip

**Comment by philipianpearce** [comment]
Hi, There is a new message (122) in v5.4.dev would you translate this as well?

Thanks, Philip

**Comment by leo95batista** [comment]
Hi @philipianpearce , I've added the translation for message 122 to the v5.4.dev branch. See PR #650... Greetings.

**Comment by philipianpearce** [comment]
Hi @dogmadev, 

Thank you very much. 

Regards 

----- Original Message -----

**Pull request merged**
